### ISSUE TITLE
enable support for kustomize secrets in additionalSecrets field

### ISSUE THREAD

**Issue by rcarpa** [rucio/helm-charts#110]
Right now, at least in atlas, we use kustomize + flux2(helmrelease) to deploy rucio using helm charts. 
The current configuration doesn't automatically restart deployments when a secret used in `additionalSecrets` is updated. This is because secretGenerator has to be run with `disableNameSuffixHash: true`

To fix this issue, we have to "teach" kustomize that fields in additionalSecrets actually point to secrets managed by itself. This way, we can get rid of `disableNameSuffixHash: true`, and dependent deployments will be automatically restarted on secret update. 

My rapid search showed that this is possible : https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/
However, I'm under the impression that the current format cannot be easily described. I "think" that a breaking change is needed for that in helm charts:

move from the format
```
    additionalSecrets:
      gcsrucio:
        secretName: gcsrucio
        mountPath: /opt/rucio/etc/gcs_rucio.json
        subPath: gcs_rucio.json
```
to
```
    additionalSecrets:
      - secretName: gcsrucio
        mountPath: /opt/rucio/etc/gcs_rucio.json
        subPath: gcs_rucio.json
```

Check if this breaking change is really needed and implement it. Otherwise document how to do it with current helm charts.
