### ISSUE TITLE
Change default of `useDeprecatedImplicitSecrets` to false.

### ISSUE THREAD

**Issue by marcoverl** [rucio/helm-charts#186]
the line https://github.com/rucio/helm-charts/blob/master/charts/rucio-daemons/templates/reaper.yaml#L117 erases the existing /etc/grid-security/certificates area when used to mount the ca-bundle.ctr via secret, making the repaer to fail the deletion in some RSEs that probably require the full content of the /etc/grid-security/certificates directory and not simply the CA bundle. It would be better to make it configurable via values.yaml

**Comment by marcoverl** [comment]
now the line is https://github.com/rucio/helm-charts/blob/master/charts/rucio-daemons/templates/reaper-deployment.yaml#L133

**Comment by maxnoe** [comment]
If you use your own secrets, I think you should switch off the `useDeprecatedImplicitSecrets` option, which would remove the line you mention.

If you currently rely on the implicit secrets, you can explicitly mount them with the `secretMounts` or `extraSecretMounts` options after switching the option off.

In our setup, it got much easier to reason about what secrets are mounted where once we switched off this deprecation option and added the explicit values.

**Comment by marcoverl** [comment]
I understand that it makes no sense to keep alive a flag called `useDeprecatedImplicitSecrets`. 
At the end a possible solution is to put it `false` and make things work by adding some explicit lines to the daemons values file: 
```
spec.values:
      secretMounts:
      - secretName: rucio-x509up
        volumeName: proxy-volume
        mountPath: /opt/proxy
      - volumeName: ca-volume
        secretName: rucio-ca-bundle
        mountPath: /opt/certs

spec.values.ftsRenewal:
      secretMounts:
      - secretName: fts-cert
        mountPath: /opt/rucio/certs/usercert.pem
        subPath: usercert.pem
      - secretName: fts-key
        mountPath: /opt/rucio/keys/new_userkey.pem
        subPath: new_userkey.pem
      additionalEnvs:
      - name: RUCIO_FTS_SECRETS
        value: <namespace>-rucio-daemons-rucio-x509up
      - name: USERCERT_NAME
        value: usercert.pem
      - name: USERKEY_NAME
        value: new_userkey.pem

spec.values.reaper:
      additionalEnvs:
      - name: X509_USER_PROXY
        value: /opt/proxy/x509up
```
while for mounting the most updated CA files on the `reaper` a possible solution is to define a cvmfs storageclass provisioned by cvmfs.csi.cern.ch, a pcv based on it, to add the lines:
```
 spec.values:
   persistentVolumes:
      public-cvmfs:
        name: cvmfs-pvc
        mountPath: /cvmfs
```
and add another environment variable as below:
```
spec.values.reaper:
      additionalEnvs:
      - name: X509_USER_PROXY
        value: /opt/proxy/x509up
      - name: X509_CERT_DIR
        value: /cvmfs/grid.cern.ch/etc/grid-security/certificates
```

**Comment by Soap2G** [comment]
Another option is to populate dynamically the nodes of the cluster with the necessary certificates using a dedicated daemonset, like [cern-authz](https://gitlab.cern.ch/kubernetes/security/cern-authz) (access to cern gitlab required), rather than with secrets, and then do:
```yaml
extraHostPathMounts:
    - hostPath: /etc/grid-security/certificates/
      mountPath: /etc/grid-security/certificates/
      readOnly: true
      type: DirectoryOrCreate
```
