### ISSUE TITLE
Automatic restart naming conflict in single application

### ISSUE THREAD

**Issue by lobis** [rucio/helm-charts#226]
When deploying rucio as a single application such as:

```
type: application

dependencies:
- name: rucio-server
  repository: https://rucio.github.io/helm-charts

- name: rucio-server
  repository: https://rucio.github.io/helm-charts
  alias: rucio-auth

- name: rucio-daemons
  repository: https://rucio.github.io/helm-charts

- name: rucio-ui
  repository: https://rucio.github.io/helm-charts
```

Some entities such as cronjobs, role bindings, etc. all share the same name prepended by the helm release. This is a problem in this pattern as there will be a naming conflict resulting in some of these entities not being created or possibly an error.

I will make a PR prepending some additional string to fix this.
