### ISSUE TITLE
Helm template produces diplicated values if using env and config

### ISSUE THREAD

**Issue by lobis** [rucio/helm-charts#242]
Found this issue in the `webui` chart, but likely is present elsewhere.

When you explicitly add an environment varaible via the `additionalEnv`:

```
  - name: RUCIO_WEBUI_RUCIO_HOST
    valueFrom:
      configMapKeyRef:
        name: rucio-hostnames
        key: rucio_server_https
```

and then define it via the config:

```
  config:
    webui:
      rucio_host: "rucio-server"
```

then helm template produces duplicates which results in error (only sometimes? Not sure why it works sometimes when doing a hard sync in argo...).

Even if you don't explicitly set the value in the `config`, it's using the default value in the chart.

A quick solution would be to remove the value from the chart (maybe setting it as `null` also works). Just leave it as a comment for documentation purposes.

A more complete solution would be to check for uniqueness in the template code or have a way to remove duplicates (in this case explicit envs should have preference).
