### ISSUE TITLE
support separation of rucio.cfg secret and non-secret content

### ISSUE THREAD

**Issue by rcarpa** [rucio/helm-charts#75]
Right now, the way to inject secret values into rucio deployed by our helm charts is by adding 
```yaml
spec:
  valuesFrom:
  - secretKeyRef:
      name: db-secret
      key: values.yaml
``` 
to the HelmRelease custom resource. The issue with this behavior is that secrets are read by helm and merged into the helm values. At this stage, we lose the information about what is a secret. As a result, we cannot use config-maps to store non-secret configuration. 

Implement a way to directly mount secrets into containers (we could rely on existing "additionalSecrets" function for that). 

A possible solution is to make our merge_rucio_configs.py scipt able to directly read secrets of the format used by `valuesFrom`:
```
config:
  database:
    default: ...
    schema: ...
```
i.e.: if it only has one top-level construct, and it's name is "config", read file['config'] instead of reading file directly.

With this change, it would be possible to gradually migrate by re-using the same secrets.
