### ISSUE TITLE
Kubernets 1.22 not supporting Ingress APIs extensions/v1beta1 

### ISSUE THREAD

**Issue by cale64** [rucio/helm-charts#80]
The helm chart for _rucio/server_ would not install on a Kubernetes cluster running on version 1.22.4 with _ingress_ enabled. The installation fails with: 

`unable to build Kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"`

According to [API removals for Kubernetes v1.22](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22) all beta _Ingress_ APIs were removed in that release. The _ingres_ template, however, still reverse to v1beta1. Could that be updated?

**Comment by cale64** [comment]
Just removed the “official” repo and now install it from a local copy in a directory. I replaced _apiVersion: extensions/v1beta1_ with _apiVersion: networking.k8s.io/v1_ in all templates and replaced

```
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
```
with 
```
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $.Values.service.port }}
```
Not sure, though, whether it should be _service.port.number_. At least installation now would not give the said error.  I’ll let you know if it works…
